name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Release packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          for dir in packages/*; do
            if [ -f "$dir/package.json" ]; then
              echo "Publishing $dir"
              cd $dir
              bunx semantic-release -e semantic-release-monorepo
              cd ../..
            fi
          done
